### ISSUE TITLE
LSA Demo Script

### ISSUE THREAD

**Issue by rrish** [willzfarmer/Python-LSA#16]
Discuss the pros and cons of an LSA demo script on a mock-up document set as a way of showing how it works before showing the final project on the entire big set.

**Comment by TheDataLeek** [comment]
Do we have a set day to present yet? What's our deadline for this project?

There are a couple things I think we should have for the presentation:
1. Slides explaining what we're doing. These should contain
   - Explanation of Algorithm
   - Motivation of Algorithm
   - Notes about the implementation of algorithm
   - Discussion of our datasets
   - Any meaningful results we were able to glean from the data.
2. A mock script that runs through a small example, possibly just a screencast of one of us manually typing in commands.
3. In person demo ready to go
4. Output of large dataset, again possible just a screencast.

**Comment by TheDataLeek** [comment]
Demo script in place.
