### ISSUE TITLE
Dynamic Document Loading

### ISSUE THREAD

**Issue by TheDataLeek** [willzfarmer/Python-LSA#2]
Currently the code only really works with the jeopardy.csv dataset that I've tweaked to be in a certain format. Ideally we make it so that it can load arbitrary document sets without much specification/tweaking.

The current expected format for a document set is one document per line. This format is open for discussion.

**Comment by rrish** [comment]
hmm ok. I am currently working on the latter part. Doing an initial implementation on Matlab and will convert it to python if it runs. So we can adjust the matrix format according to that. 

ps. I am getting a complex with the amount of work you are putting in! X_X

Regards,
Rish

**Comment by willzfarmer** [comment]
Wait, initial implementation of dynamic document loading? Or the SVD stuff? Cause the SVD stuff needs to be in different issue.

**Comment by rrish** [comment]
Of the SVD stuff. Or more accurately of what needs to be done with the SVD matrix.
We should meet sometime in the next couple of days to go over this stuff. Does tomorrow work? Or would Tuesday suit you better?

Regards,
Rish

**Comment by willzfarmer** [comment]
Let's meet tomorrow afternoon. I'll text you.

Reference #3 for SVD discussion.

**Comment by TheDataLeek** [comment]
Basically done.
