### ISSUE TITLE
SVD Analysis:- Figuring out the rank and correlation method

### ISSUE THREAD

**Issue by TheDataLeek** [willzfarmer/Python-LSA#3]
We don't know what to do with the SVD decomposition once we have it...

**Comment by rrish** [comment]
So I did the post SVD analysis. Results look promising. Implemented on a test matrix and got expected results. Will now implement it on the matrices you sent me.

**Comment by TheDataLeek** [comment]
How's that MATLAB code coming along? If you make a new branch and submit PR to master we can merge it.

Maybe put in folder `/matlab`?

**Comment by rrish** [comment]
I'll put it up today for sure! Just being lazy about it. But today 100%

On Wednesday, April 6, 2016, Will F notifications@github.com wrote:

> How's that MATLAB code coming along? If you make a new branch and submit
> PR to master we can merge it.
> 
> Maybe put in folder /matlab?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/willzfarmer/Python-LSA/issues/3#issuecomment-206396933

## 

Rishabh Raghavendran
Graduate Student
ECEE Dept.

**Comment by TheDataLeek** [comment]
Awesome! No worries, sorry to bug you. I've been super busy on other stuff lately, haven't had the time to work on this.

**Comment by rrish** [comment]
It's ok. I should be able to handle this part on my own. At least for most
of it. Will ping you as soon as I'm at a impasse  with the code and need
your help.

On Wednesday, April 6, 2016, Will F notifications@github.com wrote:

> Awesome! No worries, sorry to bug you. I've been super busy on other stuff
> lately, haven't had the time to work on this.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/willzfarmer/Python-LSA/issues/3#issuecomment-206398691

## 

Rishabh Raghavendran
Graduate Student
ECEE Dept.

**Comment by TheDataLeek** [comment]
Sounds good. Also if need git assistance, email me or check out https://github.com/willzfarmer/gitgud. (would love to hear your feedback as well, just wrote that yesterday).

**Comment by rrish** [comment]
So the results are totally random. I think I know the reason why. I think I need the list of words and documents in the same order as they are in the sparse document term matrix (before you find the SVD). Also, just wanted to confirm this but there should not be any rows or columns in the matrix with all zeros. (I am pretty sure this isn't happening but just wanted to confirm)

**Comment by TheDataLeek** [comment]
Uhhhh... hm... They should be in the same order. I'll go over the save code again and make sure that behavior is not messed up. I just made a new issue #5 to deal with this problem.

You are correct though. The order of the documents is not the same due to the parallel process. I'll go over that code ASAP.

**Comment by TheDataLeek** [comment]
I think we have the right code here, reference #8 for the next steps.

**Comment by TheDataLeek** [comment]
Since I think we have this figured out with the current Matlab code as well as the soon to be integrated Python implementation, I will close this issue.
