### ISSUE TITLE
Matlab -> Python

### ISSUE THREAD

**Issue by TheDataLeek** [willzfarmer/Python-LSA#8]
The current Matlab code needs to be converted to Python.

**Comment by TheDataLeek** [comment]
Hey @rrish how's this going? Been a couple days since we talked.

**Comment by rrish** [comment]
Hey. Super sorry. I am taking a class tomorrow for the undergrad course I am TA-ing so was swamped with that work. Will get right to working on changing the code out to python. Should have results by tonight. 

Sorry again for the delay.

**Comment by TheDataLeek** [comment]
No worries, just touching base.

Lemme know if you need a hand. I'm also on campus today if you want to meet.

**Comment by rrish** [comment]
Need to now write a script to do Doc comparisons in python. Again, this should not take much time so will have to by tonight.

**Comment by rrish** [comment]
Good to go!
